# YARD Lint configuration (New hierarchical format)
# This project uses itself for documentation linting
#
# For detailed configuration options, see:
# https://github.com/Mensfeld/yard-lint#configuration

# Global settings for all validators
AllValidators:
  # YARD command-line options
  YardOptions:
    - --private
    - --protected

  # Global file exclusion patterns (typical Ruby/Rails directories)
  Exclude:
    # Version control
    - '\.git'
    # Dependencies
    - 'vendor/**/*'
    - 'node_modules/**/*'
    # Test directories
    - 'spec/**/*'
    - 'test/**/*'
    - 'features/**/*'
    # Temporary and cache directories
    - 'tmp/**/*'
    - 'log/**/*'
    - 'coverage/**/*'
    - '.bundle/**/*'
    # Rails-specific
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'public/assets/**/*'
    - 'public/packs/**/*'
    - 'public/system/**/*'
    # Build artifacts
    - 'pkg/**/*'
    - 'doc/**/*'
    - '.yardoc/**/*'
    # Configuration that doesn't need docs
    - 'config/initializers/**/*'
    - 'config/environments/**/*'

  # Exit code behavior (error, warning, convention, never)
  FailOnSeverity: warning

# Documentation validators - checks for missing documentation
Documentation:
  Enabled: true

Documentation/UndocumentedObjects:
  Description: 'Checks for classes, modules, and methods without documentation.'
  Enabled: true
  Severity: warning

Documentation/UndocumentedMethodArguments:
  Description: 'Checks for method parameters without @param tags.'
  Enabled: true
  Severity: warning

Documentation/UndocumentedBooleanMethods:
  Description: 'Checks that question mark methods document their boolean return.'
  Enabled: true
  Severity: warning

# Tags validators - validates YARD tag quality
Tags:
  Enabled: true

Tags/Order:
  Description: 'Enforces consistent ordering of YARD tags.'
  Enabled: true
  Severity: convention
  EnforcedOrder:
    - param
    - option
    - yield
    - yieldparam
    - yieldreturn
    - return
    - raise
    - see
    - example
    - note
    - todo

Tags/InvalidTypes:
  Description: 'Validates type definitions in @param, @return, @option tags.'
  Enabled: true
  Severity: warning
  ValidatedTags:
    - param
    - option
    - return
    - yieldreturn
  ExtraTypes:
    - []

Tags/TypeSyntax:
  Description: 'Validates YARD type syntax using YARD parser (detects unclosed brackets, empty generics, etc.).'
  Enabled: true
  Severity: warning
  ValidatedTags:
    - param
    - option
    - return
    - yieldreturn

Tags/ApiTags:
  Description: 'Enforces @api tags on public objects.'
  Enabled: false  # Opt-in validator
  Severity: warning
  AllowedApis:
    - public
    - private
    - internal

Tags/OptionTags:
  Description: 'Requires @option tags for methods with options parameters.'
  Enabled: true
  Severity: warning

Tags/MeaninglessTag:
  Description: 'Detects @param/@option tags on classes, modules, or constants (only valid on methods).'
  Enabled: true
  Severity: warning
  CheckedTags:
    - param
    - option
  InvalidObjectTypes:
    - class
    - module
    - constant

Tags/CollectionType:
  Description: 'Validates Hash collection syntax (enforces Hash{K => V} over Hash<K, V>).'
  Enabled: true
  Severity: convention
  ValidatedTags:
    - param
    - option
    - return
    - yieldreturn

Tags/TagTypePosition:
  Description: 'Validates type annotation position in tags (configurable: type before or after name).'
  Enabled: true
  Severity: convention
  CheckedTags:
    - param
    - option
    # Note: @return is not included because it doesn't have a parameter name
    # @return syntax is always: @return [Type] description
  # EnforcedStyle: 'type_after_name' or 'type_first'
  # type_after_name: @param name [String] (YARD standard)
  # type_first: @param [String] name (alternative style - type before name)
  EnforcedStyle: type_after_name

# Warnings validators - catches YARD parser errors
Warnings/UnknownTag:
  Description: 'Detects unknown YARD tags.'
  Enabled: true
  Severity: error

Warnings/UnknownDirective:
  Description: 'Detects unknown YARD directives.'
  Enabled: true
  Severity: error

Warnings/InvalidTagFormat:
  Description: 'Detects malformed tag syntax.'
  Enabled: true
  Severity: error

Warnings/InvalidDirectiveFormat:
  Description: 'Detects malformed directive syntax.'
  Enabled: true
  Severity: error

Warnings/DuplicatedParameterName:
  Description: 'Detects duplicate @param tags.'
  Enabled: true
  Severity: error

Warnings/UnknownParameterName:
  Description: 'Detects @param tags for non-existent parameters.'
  Enabled: true
  Severity: error

# Semantic validators - validates code semantics
Semantic/AbstractMethods:
  Description: 'Ensures @abstract methods do not have real implementations.'
  Enabled: true
  Severity: warning
